---
- name: Configure server
  hosts: webservers
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: app, tags: ['app'] }
